# Generated by Django 5.0.6 on 2024-07-13 18:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supplier',
            new_name='seller',
        ),
        migrations.AddField(
            model_name='contact',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='retail.seller', verbose_name='Продавец'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Задолженность перед поставщиком'),
        ),
    ]
