# Generated by Django 5.0.6 on 2024-07-14 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0003_alter_contact_city_alter_contact_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_contact', to='retail.seller', verbose_name='Продавец'),
        ),
    ]
